use_frameworks!

target 'SBNag_Example' do
  pod 'SBNag.swift', :path => '../'
  pod 'SwiftDate'

  target 'SBNag_Tests' do
    inherit! :search_paths
    
    pod 'SBNag.swift', :path => '../'
    pod 'Quick'
    pod 'Nimble'
  end
end
